apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>App3</title>
      </head>
      <body>
        App 3 is greeting you
      </body>
    </html>
kind: ConfigMap
metadata:
  name: app3-cm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app3config
              mountPath: /usr/share/nginx/html
      volumes:
        - name: app3config
          configMap:
            name: app3-cm
            items:
              - key: index.html
                path: index.html
