# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
setting = YAML.load_file("#{current_dir}/config/compose.yml")

$FIREWALLSCRIPT = <<-SHELL
  sudo systemctl disable firewalld --now
SHELL


Vagrant.configure("2") do |config|
  master_ip = setting.fetch('services').fetch('master').fetch('network').fetch('ip')
  global = setting.fetch('common')
  config.vm.box = global.fetch("box")
  config.vm.box_url = global.fetch("box_url")
  config.vm.box_check_update = global.fetch("box_check_update")
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.provision "shell", inline: $FIREWALLSCRIPT

  config.vm.define "amoutikS" do |control|
    master = setting.fetch('services').fetch('master')
    control.vm.hostname = master.fetch("hostname")
    control.vm.network master.fetch('network').fetch('type'), ip: master_ip
    control.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    control.vbguest.installer_options = { allow_kernel_upgrade: true }
    # control.vm.network :forwarded_port, guest: 6443, host: 6443
    control.vm.provider "virtualbox" do |vb|
      provider = master.fetch('provider')
      vb.gui = provider.fetch('gui')
      vb.memory = provider.fetch('memory')
      vb.cpus = provider.fetch('cpus')
      # It would be nice to have a function to render an array of customizations from config.yml
      vb.customize ["modifyvm", :id, "--name", "amoutikS"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    end
    control.vm.provision :shell, path: "scripts/server_node.sh", args: [master_ip]
  end

  config.vm.define "amoutikSW" do |control|
    agent = setting.fetch('services').fetch('agent')
    node_ip= agent.fetch('network').fetch('ip')
    control.vm.hostname = agent.fetch("hostname")
    control.vm.network agent.fetch('network').fetch('type'), ip: node_ip
    control.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    control.vm.provider "virtualbox" do |vb|
      provider = agent.fetch('provider')
      vb.gui = provider.fetch('gui')
      vb.memory = provider.fetch('memory')
      vb.cpus = provider.fetch('cpus')
      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
      vb.customize ["modifyvm", :id, "--name", "amoutikSW"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    control.vm.provision :shell, path: "scripts/worker_node.sh", args: [master_ip, node_ip]
  end
end